#Test Customer API
GET http://localhost/customer-api/test

###

#Test Customer API
GET http://localhost/product-api/test

### add customer

POST http://localhost/customer-api/customer
Content-Type: application/json

{
    "customer_name":"laxman",
    "email":"ala@gmail.com",
    "mobile":8367027220,
    "address":{
        "street":"main street",
        "city":"Narasannapeta",
        "state":"AP",
        "pincode":532429
    }
}

### add customer

POST http://localhost/customer-api/customer
Content-Type: application/json

{
    "customer_name":"laxman",
    "email":"lakshmana5296@gmail.com",
    "mobile":8367027220
}
### add customer
 
POST http://localhost/customer-api/customer
Content-Type: application/json

{
    "customer_name":"lokesh",
    "email":"laxmana5296@gmail.com",
    "mobile":9052083710
}

### add product
POST http://localhost/product-api/product
Content-Type: application/json

{
    "product_name":"samsung s23",
    "product_price":90000
}

### all product
POST http://localhost/product-api/product
Content-Type: application/json

{
    "product_name":"samsung s23 ultra",
    "product_price":125000
}



### Write an review
POST http://localhost/customer-api/customer-review
Content-Type: application/json

{
    "customer_id":2,
    "product_id":2,
    "rating":4,
    "review_date":"2023-02-27",
    "review_desc":"good"
}


###  Place an order
POST http://localhost/customer-api/order
Content-Type: application/json

{
    "customer_id":1,
    "product_id":2,
    "order_date":"2023-02-28"
}
###Get all customers

GET http://localhost/customer-api/customers

### Get all products

GET http://localhost/product-api/products


###
### get reviews by customer id

GET http://localhost/customer-api/customer-reviews/2

###

###get orders by customer id

GET http://localhost/customer-api/customer-orders/1

###get orders by product id

GET http://localhost/product-api/product-reviews/2


###

GET http://localhost/customer-api/customer-reviews/<customer_id>



###

GET http://192.168.27.27:4000/customer-api/customers